<!--
SPDX-FileCopyrightText: 2025-2026 Friedrich von Never <friedrich@fornever.me>

SPDX-License-Identifier: MIT
-->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <PackageDescription>A .NET library providing XDG-like base-directory resolution for application config, data, cache, and state directories in a cross-platform way.</PackageDescription>
      <IsPackable>true</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TruePath" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FVNever.AppDirs.Tests" />
  </ItemGroup>

</Project>
